trigger:
  - develop
  - master
pr:
  - develop
  - master

pool:
  name: 'Azure Epiphany cluster - epiphany-build-agents-v2'

steps:
  - task: GoTool@0
    displayName: 'ensure Go 1.15.2'
    inputs:
      version: '1.15.2'
  - task: Go@0
    displayName: 'go get go-junit-report'
    inputs:
      command: get
      arguments: '-u github.com/jstemmer/go-junit-report'
  - task: Bash@3
    displayName: 'prepare service-principal.mk'
    inputs:
      targetType: 'inline'
      script: |
        make prepare-service-principal
      failOnStderr: true
    env:
      CLIENT_ID: $(clientId)
      CLIENT_SECRET: $(clientSecret)
      SUBSCRIPTION_ID: $(subscriptionId)
      TENANT_ID: $(tenantId)
  - task: Bash@3
    displayName: 'make test-on-azure-devops'
    inputs:
      targetType: 'inline'
      script: |
        echo $PATH
        make test-on-azure-devops
      failOnStderr: true
    env:
      K8S_VOL_PATH: '/tmp/tests-share'
      K8S_HOST_PATH: '/tests-share'
  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
