trigger:
  - develop
  - master
pr:
  - develop
  - master

pool:
  name: 'Azure Epiphany cluster - epiphany-build-agents-v2'

steps:
  - task: GoTool@0
    name: EnsureGo1_15_2
    inputs:
      version: '1.15.2'
  - task: Go@0
    name: GoGet
    inputs:
      command: 'get'
      arguments: '-u -v -f all'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
  - task: Go@0
    name: GoTest
    inputs:
      command: 'test'
      arguments: '-v -timeout 30m'
      workingDirectory: '$(System.DefaultWorkingDirectory)'
    env:
      AZURE_CLIENT_ID: $(clientId)
      AZURE_CLIENT_SECRET: $(clientSecret)
      AZURE_SUBSCRIPTION_ID: $(subscriptionId)
      AZURE_TENANT_ID: $(tenantId)
