trigger:
  - develop
  - master
pr:
  - develop
  - master

pool:
  name: 'Azure Epiphany cluster - epiphany-build-agents-v2'


variables:
  ver: dev

steps:
  - task: GoTool@0
    displayName: 'ensure Go 1.15.2'
    inputs:
      version: '1.15.2'
  - task: Bash@3
    displayName: 'Prepend PATH'
    inputs:
      targetType: 'inline'
      script: |
        echo "##vso[task.prependpath]/tools/go/1.15.2/x64/bin"
      failOnStderr: true
  - task: Go@0
    displayName: 'go get go-junit-report'
    inputs:
      command: get
      arguments: '-u github.com/jstemmer/go-junit-report'
  - task: Go@0
    displayName: 'go get govvv'
    inputs:
      command: get
      arguments: '-u github.com/ahmetb/govvv'
  - task: Bash@3
    displayName: 'go test'
    inputs:
      targetType: 'inline'
      script: |
        echo "$GOBIN"
        make build
        LDFLAGS=$(govvv -flags -pkg github.com/epiphany-platform/m-azure-basic-infrastructure/cmd -version  $(ver))
        go test -ldflags="$LDFLAGS" -v -timeout 30m 2>&1 | tee tests.output
        go-junit-report < tests.output > report.xml
      failOnStderr: true
    env:
      K8S_VOL_PATH: '/tmp/tests-share'
      K8S_HOST_PATH: '/tests-share'
      CGO_ENABLED: 0
      AZURE_CLIENT_ID: $(clientId)
      AZURE_CLIENT_SECRET: $(clientSecret)
      AZURE_SUBSCRIPTION_ID: $(subscriptionId)
      AZURE_TENANT_ID: $(tenantId)
      VERSION: $(ver)
      GOBIN: "/tools/go/1.15.2/x64/bin"
  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
      failTaskOnFailedTests: true
