trigger:
  - develop
  - master
pr:
  - develop
  - master

pool:
  name: 'Azure Epiphany cluster - epiphany-build-agents-v2'

steps:
  - task: GoTool@0
    name: EnsureGo1_15_2
    inputs:
      version: '1.15.2'
  - task: Bash@3
    name: GoGetJUnitReport
    inputs:
      script: |
        go get github.com/jstemmer/go-junit-report
  - task: Bash@3
    name: Prepare_ServicePrincipal
    inputs:
      targetType: 'inline'
      script: |
        make prepare-service-principal
      failOnStderr: true
    env:
      CLIENT_ID: $(clientId)
      CLIENT_SECRET: $(clientSecret)
      SUBSCRIPTION_ID: $(subscriptionId)
      TENANT_ID: $(tenantId)
  - task: Bash@3
    name: Test
    inputs:
      targetType: 'inline'
      script: |
        make test-on-azure-devops
      failOnStderr: true
    env:
      K8S_VOL_PATH: '/tmp/tests-share'
      K8S_HOST_PATH: '/tests-share'
  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: $(System.DefaultWorkingDirectory)/**/report.xml
